spring:
  profiles:
    active:
    - dev
---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: microcloud-config-bus-client
eureka:
  client:
    service-url:
      defaultZone: http://edmin:edmin@eureka-7301.com:7301/eureka
info:
  app.name: myspringcloud-dev-1
  company.name: www.spring.io
  app.version: v-dev-1.0.0
---
server:
  port: 8102
spring:
  profiles: beta
  application:
    name: microcloud-config-bus-client
eureka:
  client:
    service-url:
      defaultZone: http://edmin:edmin@eureka-7301.com:7301/eureka
info:
  app.name: myspringcloud-beta-1
  company.name: www.spring.io
  app.version: v-beta-1.0.0