spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: microcloud-config-eureka-client
server:
  port: 7001
security:
  basic:
    enabled: true
  user:
    name: edmindev
    password: edmindev
eureka:
  client:       # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://edmindev:edmindev@eureka-7001.com:7001/eureka
    register-with-eureka: false
    fetch-registry: false   # 不通过eureka获取注册信息
  instance:                 # eureka实例定义
    hostname: eureka-7001.com    # 定义eureka实例所在的主机名称
---
spring:
  profiles: beta
  application:
    name: microcloud-config-eureka-client
server:
  port: 7001
security:
  basic:
    enabled: true
  user:
    name: edminbeta
    password: edminbeta
eureka:
  client:       # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://edminbeta:edminbeta@eureka-7001.com:7001/eureka
    register-with-eureka: false
    fetch-registry: false   # 不通过eureka获取注册信息
  instance:                 # eureka实例定义
    hostname: eureka-7001.com    # 定义eureka实例所在的主机名称      